export const versionsRelease = [
  {
    version: '1.4.1',
    date: '2022-06-14',
    title: 'Bugfix',
    messages: ['Bugfix campaigns'],
  },
  {
    version: '1.4.0',
    date: '2022-02-19',
    title: 'Bugfix',
    messages: ['Bugfix multiplayer'],
  },
  {
    version: '1.3.3',
    date: '2022-02-09',
    title: 'Bugfix',
    messages: ['Bugfix registration', 'Bugfix login session'],
  },
  {
    version: '1.3.2',
    date: '2022-02-04',
    title: 'Improvement app',
    messages: ['Section for invite users to match', 'Bugfix'],
  },
  {
    version: '1.3.1',
    date: '2022-01-19',
    title: 'Improvement app',
    messages: ['Help during the game', 'Updated mountly tournaments', 'Bugfix'],
  },
  {
    version: '1.3.0',
    date: '2022-01-05',
    title: 'Improvement app',
    messages: ['Add campaigns', 'Bugfix', 'New random number function'],
  },
  {
    version: '1.2.0',
    date: '2021-11-06',
    title: 'Improvement app',
    messages: ['Update firebase', 'Dark mode', 'Bugfix', 'Refactor store'],
  },
  {
    version: '1.1.5',
    date: '2021-10-08',
    title: 'Improvement app',
    messages: ['Bugfix', 'Share link', 'Add touch'],
  },
  {
    version: '1.1.4',
    date: '2021-09-20',
    title: 'Bugfix',
    messages: ['Bugfix'],
  },
  {
    version: '1.1.3',
    date: '2021-08-30',
    title: 'Improvement app',
    messages: [
      'Sounds effect',
      'Save username and password',
      'Update recap match',
      'Bugfix',
    ],
  },
  {
    version: '1.1.2',
    date: '2021-08-27',
    title: 'Improvement app',
    messages: [
      'Performance',
      'SEO',
      'Feature UX',
      'Bugfix',
      'Fast match',
      'Save settings',
    ],
  },
  {
    version: '1.1.1',
    date: '2021-08-26',
    title: 'Improvement app',
    messages: [
      'New release section',
      'New report bug section',
      'Feature UX',
      'Bugfix',
    ],
  },
  {
    version: '1.1.0',
    date: '2021-07-30',
    title: 'Improvement app',
    messages: ['New navigation', 'New statistics section', 'Bugfix'],
  },
  {
    version: '1.0.4',
    date: '2021-07-23',
    title: 'Bugfix',
    messages: ['Bugfix'],
  },
  {
    version: '1.0.3',
    date: '2021-06-18',
    title: 'Change infrastructure games',
    messages: [
      'Remove Firebase for manage game rooms and integrate websocket',
      'Bugfix',
    ],
  },
  {
    version: '1.0.2',
    date: '2021-05-10',
    title: 'Refactor style',
    messages: ['Features SCSS', 'Bugfix'],
  },
  {
    version: '1.0.1',
    date: '2021-04-08',
    title: 'Add recovery password',
    messages: ['New recovery section', 'Bugfix'],
  },
  {
    version: '1.0.0',
    date: '2021-03-15',
    title: 'First version of the game',
    messages: ['-'],
  },
]
